### ISSUE TITLE
Questions on licensing (any?) and on constraining set of classes added to testArtifacts

### ISSUE THREAD

**Issue by teisemann** [hauner/gradle-plugins#5]
Hello
Thanks for creating this nice plugin.  it works great!
Couple of quesitons 
1) What license if any applies to this?  I'd like to consider it for some of our internal build process and need to go thru the usual license checking. We would not be re-distributing the plugin, just using it internally

2) Also , can I constraint the set of test classes that get included in the jar?  by default it takes all classe in src/test/java.  Is there a way I could have only some classes from src/test be included in the test artifact jar?

Thanks

**Comment by hauner** [comment]
Hi,

1. http://www.apache.org/licenses/LICENSE-2.0

2. the plugin creates a `jarTest` jar task. So you should be able too exclude classes by configuring the jar task like this
```
    jarTest {
         exclude('package/exclude/**')   
    }
```

see https://docs.gradle.org/current/dsl/org.gradle.api.tasks.bundling.Jar.html for more details on the different exclude variations.

**Comment by teisemann** [comment]
Ah Wonderful!  Thank you so much!
