### ISSUE TITLE
compile error when using compileOnly

### ISSUE THREAD

**Issue by kimhanjoon** [hauner/gradle-plugins#6]
I am using gradle 2.12 and there is compile error during compileTestJava task running when using **compileOnly** ([gradle 2.12 new feature](https://blog.gradle.org/introducing-compile-only-dependencies))

```gradle
project(':common') {
	apply plugin: 'com.github.hauner.jarTest'
}

project(':main') {
	dependencies {
		compileOnly project(':common')
		testCompile project(path: ':common', configuration: 'testArchives')
	}
}
```

But it's OK when using compile instead of **compileOnly**.

```gradle
project(':common') {
	apply plugin: 'com.github.hauner.jarTest'
}

project(':main') {
	dependencies {
		compile project(':common')
		testCompile project(path: ':common', configuration: 'testArchives')
	}
}
```

**Comment by hauner** [comment]
Hi, unfortunately I can't reproduce the issue in the demo project (see 344d15d156d70c0d3530a23dafdd8381a9c0d503). 

What does the error say?

**Comment by kimhanjoon** [comment]
You can reproduce it when SubA's ATest.java (it's in test source) depends on SubB's B.java (it's in main source).
And the error message is like below
```
C:\git\gradle-plugins\jartest-demo\SubA\src\test\java\ATest.java:8: error: cannot find symbol
                new B();
                    ^
  symbol:   class B
  location: class ATest
1 error
:SubA:compileTestJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':SubA:compileTestJava'.
> Compilation failed; see the compiler error output for details.
```

But, I found my misunderstanding of 'testArchives'. It does not conatin classess from main source, and only conatins classess from test source. I fixed the error by adding testCompile dependency also.
```gradle
project(':common') {
	apply plugin: 'com.github.hauner.jarTest'
}

project(':main') {
	dependencies {
		compileOnly project(':common')
		testCompile project(':common')
		testCompile project(path: ':common', configuration: 'testArchives')
	}
}
```

And I'm going to close this issue. Thank you.
